### PR TITLE
Add social icons

### PR DESCRIPTION
**Pull request by learn-more**
https://jira.reactos.org/browse/ONLINE-825

### CODE REVIEW

**Comment by Extravert-ir** [comment]
I don't like this one - it wastes too much space.
The icons should be moved somewhere (to bottom? to menu bar?)

**Comment by learn-more** [comment]
Feel free to create a better version

**Comment by learn-more** [comment]
@Extravert-ir do you intent to improve this?

**Comment by learn-more** [comment]
Colin fixed it

**Pull request closed without merging**
